---
title: "Test statistics, critical values, p values, oh my!"
server: shiny
format: dashboard
orientation: rows
---

```{r}
#| context: setup
library(ggplot2)
library(magrittr)
dataset <- diamonds
```

```{r}
#| label: imports

library(ggplot2)
library(shiny)
``` 


## Controls {.sidebar}
```{r}
 radioButtons( 
    inputId = "distribution_type", 
    label = "Distribution Type", 
    choices = list( 
      "T", 
      "F", 
      "Chi-squared"
    ) 
  )
```

```{r}
numericInput( 
    "df", 
    "Degrees of freedom", 
    value = 10, 
    min = 1
)

conditionalPanel(
    condition = "input.distribution_type == 'F'",
    numericInput(
        "dfd",
        "Degrees of freedom (denominator)",
        min=1,
        value=10
    )
)
```

```{r}
numericInput( 
    "siglevel", 
    "Significance level", 
    value = 0.05, 
    min = 0,
    max=1,
    step=0.01
)

radioButtons("altHypothesis",
    label = "alternate hypothesis",
    selected="neq",
    choiceNames = list(
        withMathJax("\\(\\mu_{1} \\neq \\mu_{2} \\)"),
        withMathJax("\\(\\mu{1} < \\mu{2}\\)"),
        withMathJax("\\(\\mu{1} > \\mu{2}\\)")
    ),
    choiceValues = list("neq", "lt", "gt")

)

#textInput("foo", label="test update")
```

## Rows
```{r}
plotOutput('plot')
```


```{r}
textOutput(outputId = "pval") # p value of the test statistic
textOutput(outputId = "conclusion")
numericInput('test_statistic',
label = "Test statistic value:"
, value=0)
```



```{r}
#| context: server
#| label: plot 
distribution_functions <- list(
    "t" =  list(
        d = dt,
        q = qt,
        p = pt
    )
)


dist_plot <- function (distribution, df, alt_hypo, sig_level, test_statistic=0) {
    x_min <- -4
    x_max <- 4

    d_fun <- distribution_functions[[distribution]]$d
    q_fun <- distribution_functions[[distribution]]$q

    if(alt_hypo == "neq") {
        tailness <- "two-tailed"
    } else {
        tailness <- "one-tailed"
    }

    add_critical_regions <- function(ggplot_) {
        if(tailness == "one-tailed") {
        critical_val <- q_fun(1 - sig_level, df)
        if(alt_hypo == "lt") {
            xlim <- c(x_min, -1 * critical_val)
            critical_val = -1 * critical_val
        } else {
            xlim <- c(critical_val, x_max)
        }
        return(ggplot_ + stat_function(aes(fill = "Critical region"),
                fun = d_fun,
                args = list(df = df), 
                xlim = xlim,
                geom = "area", alpha = 0.5
                
            ) +                scale_fill_manual(
                    values = c("Critical region" = "red")
                ) +
             #geom_text(aes(x=critical_val, y=0, label=paste(critical_val)))
            geom_vline(aes(xintercept=critical_val, color="Critical Value"), linetype="dashed")


        )
        } else {
            upper_critical_val <- q_fun(1 - sig_level / 2, df)
            lower_critical_val <- q_fun(sig_level / 2, df)
            return(ggplot_ + stat_function(
                fun = d_fun,
                args = list(df = df), 
                xlim = c(upper_critical_val,x_max),
                geom = "area", alpha = 0.5,
                aes(fill = "Critical Region")
            ) +
            stat_function(
                fun = d_fun,
                args = list(df = df), 
                xlim = c(x_min,lower_critical_val),
                geom = "area",
                fill = "red",
                alpha = 0.5
            ) +
            geom_vline(aes(xintercept=upper_critical_val, color="Critical Value"), linetype="dashed") +
            geom_vline(aes(xintercept=lower_critical_val, color="Critical Value"), linetype="dashed") +
             geom_text(aes(x=upper_critical_val, y=0, label=paste(upper_critical_val))) +
             geom_text(aes(x=lower_critical_val, y=0, label=paste(lower_critical_val)))
            )
        }

    }
    ggplot_ <- ggplot() +
        xlim(x_min, x_max) +
        stat_function(fun=d_fun, args=list(df=df)) +
        labs(
            title = "t distribution"
        ) + geom_vline(
            aes(
                xintercept=test_statistic, color="Test Statistic"
            ),linetype='dashed'
            

        ) +
            geom_text(aes(x = test_statistic, y = 0, label = "hi")) + scale_color_manual(
                 values = c("Critical Value" = "red", "Test Statistic" = "blue")
                )
    add_critical_regions(ggplot_)

}

```

```{r}
#| context: server
#| 
#dist_plot('t', df=10, tailness="one-tailed", 0.05)

#dist_plot('t', df=10, tailness="two-tailed", 0.05)


```

```{r}
#| context: server

df <- reactive(input$df)
sig_level <- reactive(input$siglevel)
tailness <- reactive(input$tailness)
test_statistic <- reactive(input$test_statistic)
distribution_type <- reactive(input$distribution_type)

alt_hypo <- reactive(input$altHypothesis)
```
```{r}
#| include: FALSE
#| context: server
# Create a base plot with the desired x-axis range
output$debug <- renderText(df())
output$plot <- renderPlot(
    dist_plot('t', df(), alt_hypo=alt_hypo(), sig_level=sig_level(), test_statistic=test_statistic())

)
output$pval <- renderText(
    paste("p-value: ",
    distribution_functions[['t']]$p(test_statistic(), df(), lower=FALSE))
)
output$conclusion <- renderText(
    "yes"
)
#observe({
#    updateTextInput(inputId="foo", value=input$distribution_type)
#}) %>% bindEvent(input$distribution_type)
```